### PR TITLE
[Feature Proposal] Export DEFAULT_TEQUILA_MIRROR_OPTIONS like mirrorcli

### PR DESCRIPTION
**Pull request by 0xslipk**
Hi guys,

This PR export from Mirror Client the `DEFAULT_TEQUILA_MIRROR_OPTIONS` like [mirrorcli](https://github.com/Mirror-Protocol/mirrorcli/blob/main/src/data/mirrorclirc.ts#L6-L144) does.

### CODE REVIEW

**Comment by 0xslipk** [comment]
@hanjukim please take a look when you get a chance 😄

**Comment by hanjukim** [comment]
@simcheolhwan could you confirm that addresses are correct?

**Comment by simcheolhwan** [comment]
> @simcheolhwan could you confirm that addresses are correct?

The assets are correct.
But mSPY, mCOIN is not included. 

@jarcodallo Would you include them and make a new commit into this branch?

**Comment by 0xslipk** [comment]
> > @simcheolhwan could you confirm that addresses are correct?
> 
> 
> 
> The assets are correct.
> 
> But mSPY, mCOIN is not included. 
> 
> 
> 
> @jarcodallo Would you include them and make a new commit into this branch?

Yes sure. I will do it

**Comment by 0xslipk** [comment]
@simcheolhwan I added the mAssets to tequila and columbus options.

**Comment by simcheolhwan** [comment]
Yes they are correct

**Comment by 0xslipk** [comment]
@hanjukim ready to merge 🚀

**Review by hanjukim — APPROVED** [review]

**Pull request merged**
